{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-security",
    "version": "3.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.5"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.4.jar",
          "url": "spring-boot-starter-security-3.2.4.jar",
          "size": 4741,
          "sha512": "0b6884512cd6a2572d8098339bf08dce0e2f1815ff82ad080a5c921f19869ecb232534848d5d049a003df2a4fd4ef49c55b1b31e27b0e9532e34c5b1f10ce518",
          "sha256": "cfbbba6ded54aebc4d3ee4748e5a6370c2079b2692f2c50f1315dcbb326de74d",
          "sha1": "a1b9f09832c42c6c079be67bf3e7989c54a338ff",
          "md5": "62c8356121104d8248c1175d5b2b7fa5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.5"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.4.jar",
          "url": "spring-boot-starter-security-3.2.4.jar",
          "size": 4741,
          "sha512": "0b6884512cd6a2572d8098339bf08dce0e2f1815ff82ad080a5c921f19869ecb232534848d5d049a003df2a4fd4ef49c55b1b31e27b0e9532e34c5b1f10ce518",
          "sha256": "cfbbba6ded54aebc4d3ee4748e5a6370c2079b2692f2c50f1315dcbb326de74d",
          "sha1": "a1b9f09832c42c6c079be67bf3e7989c54a338ff",
          "md5": "62c8356121104d8248c1175d5b2b7fa5"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.4.jar",
          "url": "spring-boot-starter-security-3.2.4.jar",
          "size": 4741,
          "sha512": "0b6884512cd6a2572d8098339bf08dce0e2f1815ff82ad080a5c921f19869ecb232534848d5d049a003df2a4fd4ef49c55b1b31e27b0e9532e34c5b1f10ce518",
          "sha256": "cfbbba6ded54aebc4d3ee4748e5a6370c2079b2692f2c50f1315dcbb326de74d",
          "sha1": "a1b9f09832c42c6c079be67bf3e7989c54a338ff",
          "md5": "62c8356121104d8248c1175d5b2b7fa5"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-security-maven-optional",
          "version": "3.2.4"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.4.jar",
          "url": "spring-boot-starter-security-3.2.4.jar",
          "size": 4741,
          "sha512": "0b6884512cd6a2572d8098339bf08dce0e2f1815ff82ad080a5c921f19869ecb232534848d5d049a003df2a4fd4ef49c55b1b31e27b0e9532e34c5b1f10ce518",
          "sha256": "cfbbba6ded54aebc4d3ee4748e5a6370c2079b2692f2c50f1315dcbb326de74d",
          "sha1": "a1b9f09832c42c6c079be67bf3e7989c54a338ff",
          "md5": "62c8356121104d8248c1175d5b2b7fa5"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-security-maven-optional",
          "version": "3.2.4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.4-javadoc.jar",
          "url": "spring-boot-starter-security-3.2.4-javadoc.jar",
          "size": 4745,
          "sha512": "d20f97532d255455df6beee5b3e608cb23be5f96a6b44b07b449d2fd7c0ac6f833e2dd4e4bc8921866e4db834449f639d1a26f41846ba5a719faeb593320d968",
          "sha256": "96a0381464469778f7f96f8d618c4ea34750a5a985d277727fe216f1fb59d01f",
          "sha1": "16b4bd293593cb12f7711bcc1e7e04c5bcf4f840",
          "md5": "455ffb504fc63c1b833c56afd988b16a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.4-sources.jar",
          "url": "spring-boot-starter-security-3.2.4-sources.jar",
          "size": 4743,
          "sha512": "c16b70f35b2701d43a228839f78ca13bc41e07178e08ed1c8fa330b4b84a2539256c9659fb8cad5aae89d17424bda530b7a0d5ba41b208054e1ee11050bec068",
          "sha256": "d90c65e9e7d593f852cfe808bfcfbafe3d1ff734a806bf484c11e9508afabb25",
          "sha1": "54aa8489e92a2a3ae357916b92e8c23b306d0eb8",
          "md5": "ba8b72bf212cc9aff3a0f3054d5ac2d0"
        }
      ]
    }
  ]
}
